export default function Contact() {
    return (
        <div>
            <div className="font-bold text-2xl text-white">Contact US</div>
            <div className="font-medium text-lg text-white">This is contact us page.</div>
            <div className="font-medium text-lg text-white">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi lacinia sagittis massa, sed maximus tellus faucibus quis. Vivamus imperdiet eros vel nisi tempor, finibus auctor lorem scelerisque. Aenean mi metus, vehicula nec ipsum accumsan, pretium tincidunt nulla. Vestibulum elementum venenatis felis, sed tincidunt massa rhoncus id. Donec sed mi elit. Proin pellentesque eros vitae nulla condimentum sagittis. Donec diam lacus, tincidunt quis volutpat eu, tempus non nisl. Pellentesque fringilla lorem est. Vestibulum euismod ultrices venenatis. Pellentesque rhoncus nulla eu tellus ultrices, eu sagittis libero fermentum. Nullam condimentum consectetur nisl non viverra. Aenean a eros vel metus gravida laoreet. Praesent ultricies, nulla et elementum vestibulum, felis justo auctor augue, at volutpat nibh ligula sagittis enim. Maecenas id aliquam eros, volutpat efficitur urna. Praesent felis massa, vehicula elementum erat sed, congue sollicitudin metus.</div>
            <div className="font-medium text-lg text-white">Nulla diam erat, ultrices in pharetra ut, malesuada a massa. Quisque rutrum libero in risus facilisis, vel malesuada sem ultrices. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec eu sagittis arcu, vitae consectetur urna. Nunc vel arcu in tellus tincidunt iaculis. Etiam sollicitudin elit porta dictum scelerisque. Pellentesque rutrum purus id eros vehicula tincidunt. Mauris ultrices lectus vel nisi congue, ac iaculis lectus aliquet. Ut ac dui aliquam, efficitur eros sit amet, placerat ex. Mauris non dapibus augue. Ut nisl est, feugiat at tincidunt a, auctor sit amet odio. Ut ullamcorper nisi id vulputate rhoncus. Sed blandit venenatis erat in sodales. Etiam a metus nec est consequat scelerisque in eleifend lectus.</div>
            <div className="font-medium text-lg text-white">Aliquam pellentesque risus et egestas tristique. Maecenas viverra arcu eget imperdiet rhoncus. Sed dapibus massa urna, at volutpat augue condimentum id. Integer facilisis venenatis elit. In ultrices, lacus in rutrum varius, neque dolor vehicula mauris, quis faucibus tortor nulla nec eros. Integer volutpat tristique ligula. Nulla nulla lorem, accumsan id ante id, vestibulum laoreet sapien. Proin auctor porta urna eget ultrices. Nunc sit amet consequat quam, et vestibulum tellus. Pellentesque consectetur imperdiet lectus, sed malesuada dolor varius at. Mauris tellus enim, scelerisque ut sem at, cursus malesuada eros. Curabitur condimentum, purus eget placerat scelerisque, erat massa eleifend est, et maximus magna massa viverra ex.</div>
            <div className="font-medium text-lg text-white">Aenean tincidunt risus ligula, eget pharetra purus elementum vitae. Cras id elit nibh. Phasellus tempus lacus nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam tristique dolor enim, quis sodales ex luctus sed. Ut hendrerit varius ultrices. Proin nec tellus eget lectus aliquam varius. Ut a nisl ligula. Aliquam eget vehicula lorem, nec rutrum libero. Donec elit ligula, egestas mollis consectetur ac, condimentum eget ligula. Donec pharetra leo nec laoreet tempus. Donec nec diam tincidunt, fringilla mauris sed, aliquet ipsum. Integer pellentesque dolor id sodales pretium. Nam eget imperdiet tortor.</div>
            <div className="font-medium text-lg text-white">Duis faucibus, erat sed auctor posuere, mi ex tempor felis, ut bibendum nibh ex id ante. Quisque nec neque vel eros porta commodo at vitae arcu. Fusce eget neque sed nisi venenatis egestas. Duis auctor lectus est, sit amet pharetra leo suscipit nec. Nulla id magna mi. Suspendisse convallis volutpat velit. Sed vehicula dui molestie orci auctor scelerisque. Donec interdum dui ut porta semper. Donec lorem purus, tincidunt in lectus vitae, interdum malesuada felis. Morbi non neque lorem. Vestibulum fermentum justo nisl, et aliquet tortor luctus ac. Aliquam tincidunt sagittis felis at placerat. Praesent eget ex quam. Phasellus eget pellentesque tellus, sit amet efficitur elit.</div>
        </div>
    )
}